# Generated by Django 6.0 on 2026-01-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_permis', models.CharField(max_length=50)),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('type_client', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=50)),
                ('tarif_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_incident', models.DateField()),
                ('piece_jointe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_reclamation', models.DateField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournee', models.DateField()),
                ('kilometrage', models.FloatField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('tarif_poids', models.FloatField()),
                ('tarif_volume', models.FloatField()),
                ('delai_estime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('capacite_poids', models.FloatField()),
                ('capacite_volume', models.FloatField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expedition', models.CharField(max_length=50)),
                ('date_expedition', models.DateField()),
                ('poids', models.FloatField()),
                ('volume', models.FloatField()),
                ('montant_ht', models.FloatField()),
                ('statut', models.CharField(max_length=50)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.client')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.destination')),
                ('id_typeservice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.typeservice')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField()),
                ('montant_ht', models.FloatField()),
                ('tva', models.FloatField()),
                ('montant_ttc', models.FloatField()),
                ('statut', models.CharField(max_length=50)),
                ('id_expedition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.expedition')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.FloatField()),
                ('mode_paiement', models.CharField(max_length=50)),
                ('id_facture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.facture')),
            ],
        ),
    ]
