# Generated by Django 6.0 on 2026-01-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.FloatField()),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.destination')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.typeservice')),
            ],
        ),
    ]
