# Generated by Django 6.0 on 2026-01-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='id_expedition',
        ),
    ]
