# Generated by Django 6.0 on 2026-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_facture_id_expedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='montant_ht',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
