# Generated by Django 6.0 on 2026-01-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_expedition_montant_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='id_Tournee',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.tournee'),
        ),
    ]
