# Generated by Django 6.0.1 on 2026-01-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('balance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price_per_weight', models.FloatField()),
                ('price_per_volume', models.FloatField()),
                ('estimated_delay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('max_weight', models.FloatField()),
                ('max_volume', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('amount_ht', models.FloatField()),
                ('amount_vat', models.FloatField()),
                ('amount_ttc', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.destination')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('shipment_date', models.DateField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('amount_ht', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.destination')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('complaint_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField()),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tour'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.shipment')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tour')),
            ],
        ),
    ]
