# Generated by Django 6.0 on 2026-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_base_price_delete_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='amount_ht',
            field=models.FloatField(blank=True),
        ),
    ]
