# Generated by Django 6.0 on 2026-01-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_id_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incidents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.incident')),
            ],
        ),
    ]
