# Generated by Django 6.0 on 2026-01-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shipment_amount_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_ht',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_ttc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_vat',
            field=models.FloatField(blank=True),
        ),
    ]
