# Generated by Django 6.0.1 on 2026-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_complaint_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='piece_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
