# Generated by Django 6.0.1 on 2026-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incident_photo_url_incident_piece_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
    ]
