# Generated by Django 6.0 on 2026-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invoice_amount_ht_alter_invoice_amount_ttc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_ht',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_ttc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
