# Generated by Django 6.0 on 2026-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invoice_amount_ht_alter_invoice_amount_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_vat',
            field=models.FloatField(blank=True, default=0.19),
        ),
    ]
