# Generated by Django 6.0.1 on 2026-01-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_incident_photo_url_incident_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rest',
            field=models.FloatField(default=0),
        ),
    ]
