# Generated by Django 6.0 on 2026-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incident_status_alter_invoice_amount_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_ht',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_ttc',
            field=models.FloatField(default=0, null=True),
        ),
    ]
