# Generated by Django 6.0.1 on 2026-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='carb',
            field=models.FloatField(default=0, verbose_name='Fuel Consumption (L)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='incd',
            field=models.IntegerField(default=0, verbose_name='Number of Incidents'),
        ),
        migrations.AddField(
            model_name='tour',
            name='nb_exp',
            field=models.IntegerField(default=0, verbose_name='Number of Expeditions'),
        ),
    ]
