# Generated by Django 6.0 on 2026-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_invoice_amount_ht_alter_invoice_amount_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='amount_ht',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
