# Generated by Django 6.0.1 on 2026-01-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tour_carb_tour_incd_tour_nb_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(),
        ),
    ]
