# Generated by Django 6.0 on 2026-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_shipment_amount_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='amount_ht',
            field=models.FloatField(default=0),
        ),
    ]
