# Generated by Django 6.0 on 2026-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_shipment_amount_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_ht',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_ttc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_vat',
            field=models.FloatField(default=0.19),
        ),
    ]
