# Generated by Django 6.0 on 2026-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_invoice_amount_ht_alter_invoice_amount_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='solld',
            field=models.FloatField(default=0),
        ),
    ]
