# Generated by Django 6.0 on 2026-01-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_payment_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='base_price',
            new_name='base_rate',
        ),
    ]
