# Generated by Django 6.0 on 2026-01-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_base_price_destination_base_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
    ]
